### ISSUE TITLE
Link to chapter 7 page error

### ISSUE THREAD

**Issue by lukaszsobek** [DomanskaGrzyb/awesome-google-mobile-web-challenge-links-2017#14]
The README.md link to chapter 7 has an x too much.

It is: https://github.com/DomanskaGrzyb/awesome-google-mobile-web-challenge-links-2017/blob/master/built-insx/README.md

it should be : https://github.com/DomanskaGrzyb/awesome-google-mobile-web-challenge-links-2017/blob/master/built-ins/README.md

("built-ins" instead of "built-insx")

**Comment by Agheb** [comment]
fixed  5342e9f008f85e61fb23643a27ea23762221647b
