### ISSUE TITLE
Accept submissions via Github issue tracker ?

### ISSUE THREAD

**Issue by Agheb** [DomanskaGrzyb/awesome-google-mobile-web-challenge-links-2017#17]
What do you think? Let's discuss this...

**Comment by Haitec** [comment]
I think that's a good idea. no need to fork, commit, pull request. 👍

**Comment by adomanskagrzyb** [comment]
I also like the idea!!! Are there any things that may become more complicated / discouraging for our users because of this approach?

**Comment by jvaes** [comment]
Great idea, Miguel is right no more pull requests!
