### ISSUE TITLE
Should we avoid linking to the forum ?

### ISSUE THREAD

**Issue by adomanskagrzyb** [DomanskaGrzyb/awesome-google-mobile-web-challenge-links-2017#28]
As you may know, our access to the forum may be limited in the future. I'm wondering wouldn't it be better to copy-paste useful content from the forum to the repo (adding somewhere on the beginning name of the original author of each text) instead of linking to them?

Nonetheless, I would keep a general link to the forum.

**Comment by bogdaaamn** [comment]
The managers said that they are looking into fixing the problems with the forum.

**Comment by Haitec** [comment]
I'm against to copy-pase, because the limitation of access in the forum has a reason.

**Comment by Agheb** [comment]
Don't copy paste without asking for permission. I'd rather avoid links to the forum

**Comment by alexanderluna** [comment]
I think a link to the forum is better than copying and pasting everything from the forum here.
We want to keep everything clean here

**Comment by alexanderluna** [comment]
For example: The Q&A links should link to the Google Drive File rather than to a separate README where the entire Q&A is pasted.

**Comment by adomanskagrzyb** [comment]
If we will have access to the forum even after the scholarship will end - then it's good to add links. If we won't have access, then we should find a different solution how to avoid losing most useful content.

**Comment by adomanskagrzyb** [comment]
Regarding Q&A example - Google Drive File is one solution (thank you @Mycroft1891). PDF stored on AWS?

**Comment by alexanderluna** [comment]
Ohh right, I forgot forum access might be killed. Sorry. Yes for Q&A AWS or Google Drive with a public link would be enough. As for forums, we will have to copy and paste but maybe we can copy and paste the forum's content in a file and upload it to Google Drive or AWS. We can then link to the file in the repo

**Comment by Agheb** [comment]
My problem with Google Drive is this:
<img width="1434" alt="image 2017-11-08 at 3 08 11 pm" src="https://user-images.githubusercontent.com/2975703/32553383-0d4b70d8-c497-11e7-8fe9-a4cd41af1cc2.png">

Great for editing documents but not for viewing the content

**Comment by Mycroft1891** [comment]
Its because you are using a google doc to save. Use PDF when saving the file

**Comment by alexanderluna** [comment]
You don't have that problem when you save the files as PDF
<img width="1440" alt="screen shot 2017-11-08 at 3 11 25 pm" src="https://user-images.githubusercontent.com/11302907/32553410-2a0e3d90-c497-11e7-82f2-70564fa42e42.png">

**Comment by alexanderluna** [comment]
For example I downloaded the AMA session and exported it as a PDF, what do you think: 
https://drive.google.com/file/d/1dDWySCg16khjWeaJM9WMnPrFJOrrRL1e/view?usp=sharing

**Comment by Agheb** [comment]
AWS is not necessary. We can host them here as assets.  But binary file formats like pdfs are not really useful for version control.

**Comment by alexanderluna** [comment]
I think a public link to the PDF files does the trick. We don't have to always upload and download the AMA sessions from the repo and everyone can access it from google drive/mega/AWS (whatever we go with)

**Comment by alexanderluna** [comment]
We can actually remove the AMA folder because all AMA sessions are stored inside a single file. Or do you want me to split them into seperate PDFs ?

**Comment by adomanskagrzyb** [comment]
I would remove the folder, keep a single file and split the content inside this file by adding headers for each session (to make it easier to find each of them).

**Comment by alexanderluna** [comment]
Remove the folder, instead of linking to the README.md link to the Google Drive PDF I created. I will update it when the next AMA is out.
