### ISSUE TITLE
Duplicate link in javascriptSyntax section

### ISSUE THREAD

**Issue by odv** [DomanskaGrzyb/awesome-google-mobile-web-challenge-links-2017#30]
Yesterday I've added 'The Moder JavaScript Tutorial' to the list of resources under 'javascriptSyntax': https://github.com/DomanskaGrzyb/awesome-google-mobile-web-challenge-links-2017/pull/21

Today when I was looking, it has been added again. Not sure why.
I've submitted a PR to remove the duplicate link

**Comment by alexanderluna** [comment]
Sorry must have been me when I merged today

**Comment by alexanderluna** [comment]
I removed it in my pull request you can remove your pull request if you like

**Comment by Agheb** [comment]
Fix 6f1939d10f60feccf24742b37a12b100bb81021b
