### ISSUE TITLE
Additional folder for useful tools

### ISSUE THREAD

**Issue by adomanskagrzyb** [DomanskaGrzyb/awesome-google-mobile-web-challenge-links-2017#35]
People are sharing links to useful tools, we could collect them in one place and split based on operating system / just list them and tag on what OS are they working / just list them.

**Comment by jvaes** [comment]
Good idea, I would split them based on the operating system.

**Comment by adomanskagrzyb** [comment]
This may be useful for you @jvaes when you will split links. Closing for now, but please keep it in your mind! :)
