### ISSUE TITLE
GitHub Page

### ISSUE THREAD

**Issue by Haitec** [DomanskaGrzyb/awesome-google-mobile-web-challenge-links-2017#37]
We should make this a "GitHub Page".
What do you think?

https://pages.github.com/

**Comment by bogdaaamn** [comment]
The default themes are pretty basic if you ask me. But what do you have in mind tho?

**Comment by Haitec** [comment]
It would be easier for the people not that skilled in GitHub.

**Comment by Agheb** [comment]
If you're in the Web Developer Intermediate Track, you should be familiar with Git and Github.  We still can provide help and guidance on Slack (channel #resources) if someone is lost here.

**Comment by Agheb** [comment]
We can whip up a GH Page if we have enough content to show the world what we are working on and who we are 😉
