### ISSUE TITLE
Additional links - promises and SW

### ISSUE THREAD

**Issue by Sugahzor** [DomanskaGrzyb/awesome-google-mobile-web-challenge-links-2017#40]
**Promises:** 

- https://www.quora.com/What-is-callback-hell1
- http://javascriptissexy.com/understand-javascript-callback-functions-and-use-them/1
- https://scotch.io/tutorials/javascript-promises-for-dummies1
- https://medium.com/javascript-scene/master-the-javascript-interview-what-is-a-promise-27fc71e772612
- https://dev.to/azizhk110/javascript-promise-chaining--error-handling?utm_content=buffer50085&utm_medium=social&utm_source=facebook.com&utm_campaign=buffer1
- https://www.youtube.com/watch?v=8aGhZQkoFbQ1 (AWESOME video)

**SW specific:**

- https://www.youtube.com/watch?v=jVfXiv03y5c1 (leads you to more great resources)
- https://serviceworke.rs/3 (leads you to a Git repo with examples)

**Comment by adomanskagrzyb** [comment]
Thank you @Sugahzor !

**Comment by Sugahzor** [comment]
Thank you for this great repo!

**Comment by adomanskagrzyb** [comment]
@Sugahzor could you please share with us your full name? We would like to add you to `Thanks to contributors` list.

**Comment by Haitec** [comment]
Where will these links be (especially `Promises`)?

_Note: Don't forget to remove the last digit -> count of clicks from forum_ 😉

**Comment by adomanskagrzyb** [comment]
Good catch, thank you @Haitec ! 

I would put `Promises` in `Further Learning` folder for now, but maybe move to some other place in the future - **I'd like to open a discussion on how we should manage links that are useful but are not so tightly related to course / our course folders.** Please check it here: https://github.com/DomanskaGrzyb/awesome-google-mobile-web-challenge-links-2017/issues/45

**Comment by Sugahzor** [comment]
Heya :) My name is iulia voicu , thank you for adding me!
I for one see promises directly connected with the Service Workers, as one cannot understand SW without understanding promises. It's a prerequisite, in my opinion.

**Comment by adomanskagrzyb** [comment]
Yes, it is a prerequisite, but temporarily I've added it as a `further learning` - we can change it later on. I think that we should discuss in separate issue should we create some kind of `prerequisite` folder or should we just add all topics that are close (but not directly explaining topic) to one folder and just split them right / link to them in lessons folders.

**Comment by Haitec** [comment]
Promises are in `Lesson 8.17-19`.
