### ISSUE TITLE
🎉 🎉 🎉 Calling for volunteers 🎉 🎉 🎉

### ISSUE THREAD

**Issue by adomanskagrzyb** [DomanskaGrzyb/awesome-google-mobile-web-challenge-links-2017#41]
We need somebody (could be few people) who could help us with categorizing links. I have a document that I can share with a volunteer, and what this person is asked to do is:
1. open each link
2. decide is it useful, if so then
3. check isn't it already in our repo
4. categorize it properly (add in a chosen place)
5. prepare pull request 

🎉 🎉 🎉 Some of the links may be duplicated. Some of them may be not so useful. Some of them may be useful, but there is no proper category/place for them yet (and you will have a chance to create it). You could be responsible for what other people will see and how our repo may look like, so if you want to do something great for this community - this is your chance!!! 🎉 🎉 🎉

**Comment by jvaes** [comment]
Hi Anna, If you send me the document I can look in to it. If u want several volunteers working on this I think we should split it into categories and each volunteer should be responsible for a single category. This to prevent some tasks from being executed multiple times.

**Comment by adomanskagrzyb** [comment]
Ok, I'm closing this issue for now. If we will need more help, you are welcome to create new issue @jvaes :)

**Comment by adomanskagrzyb** [comment]
Reopening because all friendly heads and hands are welcome!

**Comment by cmmata** [comment]
I can help too! I'm `@carles` in Slack.

**Comment by alexandrufulop** [comment]
Hi Anna, 
Could you share the links document please.
Thank you!

**Comment by alexanderluna** [comment]
Send me the list I can do it quick
