### ISSUE TITLE
Further learning folder

### ISSUE THREAD

**Issue by adomanskagrzyb** [DomanskaGrzyb/awesome-google-mobile-web-challenge-links-2017#45]
I'm thinking of **'Further learning folder'** as a place where we can add all interesting resources that are not directly connected with topics of this course. The question is - maybe instead of splitting it based on type (book, video etc) we should split them based on categories (html, css, js...) with internal topics (css methodologies, flexbox etc)? Or maybe we should 'tag' somehow those resources? For now, this readme is quite thin, but I assume that it may grow soon so this is the best moment to think about it.

Another question is - should we have some kind of `prerequisite folder` (check [this issue](https://github.com/DomanskaGrzyb/awesome-google-mobile-web-challenge-links-2017/issues/40) and [this pull request](https://github.com/DomanskaGrzyb/awesome-google-mobile-web-challenge-links-2017/pull/46)) or should we add all links that are close (but not directly explaining topic) to one folder and just split them right / link to them in lessons folders.

**Comment by Sugahzor** [comment]
I think the categories + internal topics would be very good and clear. I can provide more resources if we make the Further Learning folder.
P.S.: Would have loved to volunteer with sorting links, but I'm a complete Git noob and was afraid of messing things up. But if I can help with just sorting/categorizing, I'm up for it :)

**Comment by jvaes** [comment]
@Sugahzor all help is welcome sorting the links, there are a whole lot of them! #

**Comment by adomanskagrzyb** [comment]
Yes, there is a lot of them and will be even more. @Sugahzor please write to me on a slack, I will explain you the details. Thank you for your willingness to help!!!

**Comment by alexanderluna** [comment]
Sounds good, lessons and tutorials, videos all seem to be just one folder at times. I agree that we should group by html&css, JavaScript, data rendering (like d3 and p5)

**Comment by jvaes** [comment]
I went through to the further learning folder and saw some of the topics ware very basic. In my opinion further learning should extend the content of the course and the topics should be more advanced. The students who complete the course and want to learn further, already know things like AJAX and promises.

**Comment by Sugahzor** [comment]
I'll say it here also. I really think you guys should make Lesson 0 : Prerequisites and add everything related to promises/AJAX there. There are a lot of people (seen them asking on Slack) who haven't even heard of promises. 
As for the Further Learning structure/content , I may have misunderstood it's designation. I thought it should contain any awesome links related to JS/HTML/CSS in general. Even so, I understand now my filter when sorting those links should have been a lot more strict. 
I'll do a better job of sorting links-to-come after you guys decide what Further Learning should contain :)

**Comment by alexanderluna** [comment]
Lesson 1 is Lesson 0 because the Intro was just 2 videos. We should post all prerequisites in lesson 1

**Comment by alexanderluna** [comment]
@jvaes I agree, I moved links that had to do with promises, callbacks and ajax from ```further learning``` into ```introduction``` since those are topics a student has to know before taking the course.

**Comment by adomanskagrzyb** [comment]
Ok, I have a feeling that we found a solution here - we're using `further learning` for advanced topics and `introduction` for basic ones. 

Nonetheless, shouldn't we split it into html/ccs/js or more advanced groups instead of books/questions etc (both on `further learning` and `introduction` folders)?

**Comment by alexanderluna** [comment]
I have updated the format of the `further leaning` readme slightly in my pull request. I split everything into HTML&CSS, Javascript and Youtube Channels with a header file for quick access.
