### ISSUE TITLE
Repo structure

### ISSUE THREAD

**Issue by alexandrufulop** [DomanskaGrzyb/awesome-google-mobile-web-challenge-links-2017#51]
Hi everyone, 

First of all thank you Ania for this repo and all of you for your contributions!

What would think if we organize this repository and create a Lesson based folder structure for the course?
For example we could create a folder for each lesson an a structure similar to this:

```
Lessons
    Lesson 1 
       ---readme.ME
    Lesson 2
       ---readme.ME
```

or a more deeper structure like
```
Lessons
   Lesson 1         
      ---1.1
          ---readme.ME
          ---resources.ME
          ---examples.ME
      ---1.2
          ---readme.ME
```
...

Looking forward to your feedback!

Regards,
Alexandru

**Comment by Sugahzor** [comment]
We were talking about the Promises being tighter related to the Service Workers, as maybe some not-so-advanced students would have difficulties finding where Promises related resources are (atm in Further Learning). 
Also, we should take up Ania's idea to structure Further Learning into JS / HTML / CSS topics as it would be more clear.
But what do you think of a Lesson 0: Prerequisite for the course ( we'd include promises there )?

**Comment by alexanderluna** [comment]
I don’t know because right now we don’t have that much material and we already divided everything into lessons. Each sub lesson (1.1) is usually only a short video 2-5 min or an exercise. We can just add headers to the README.md and add them below

**Comment by Sugahzor** [comment]
What about Lesson 0 ?

**Comment by Agheb** [comment]
@alexandrufulop  I think deeply nested folder structures are not relevant for the majority. We work with linked markdown files and it brings no value to users because they rather view the repo then clone it.

**Comment by alexandrufulop** [comment]
What I was suggesting was a better root structure of our repo.
I think the folders would be more relevant if their names would be prefixed with the Lesson number like: 
```
L1-Introduction
L2-OfflineFirst
L3-ServiceWorker
...
```
but again everyone has his own logic...
The first lessons are basic, but later on things change...

**Comment by alexanderluna** [comment]
@alexandrufulop Right now, the structure is already very similar:
```
Lesson 1: Introduction
Lesson 2: Offline First
Lesson 3: Service Worker
Lesson 4: IndexedDB & Caching
Lesson 5: Javascript Syntax
Lesson 6: Functions
Lesson 7: Built-ins
Lesson 8: professional-developer-fu
Further learning
Q&A Sessions
```

**Comment by adomanskagrzyb** [comment]
As our current naming convention is quite similar to one proposed by you @alexandrufulop I think that we can close this discussion.

But thank you for your suggestion Alexandru! Keep on rocking! 🎉 🎉 🎉
