### ISSUE TITLE
Youtube Channel Fun Fun Function

### ISSUE THREAD

**Issue by Agheb** [DomanskaGrzyb/awesome-google-mobile-web-challenge-links-2017#61]
Swedish Guy, who's not afraid of teaching advanced JS topics in a fun way. 
My favourite videos are the ones about Functional Programming in JS. 

https://www.youtube.com/channel/UCO1cgjhGzsSYb1rsB4bFe4Q

**Comment by alexanderluna** [comment]
I created a Youtube section in the ```further learning``` README for useful Youtube Channels. You should add it there
