### ISSUE TITLE
Where to add a free daily book link

### ISSUE THREAD

**Issue by cmmata** [DomanskaGrzyb/awesome-google-mobile-web-challenge-links-2017#65]
Hello!

I wanted to add a link in `Further learning`, but I'm not sure where to put it. Packt is a development book editorial that offers a [free ebook per day](https://www.packtpub.com/packt/offers/free-learning). Should I put it into `Books`? As it's not only one book, I don't know if it should be in another section.

What do you think?

**Comment by alexanderluna** [comment]
I put the link inside the books sections in the ```further learning``` README
